spring:
  profiles:
    active: local # 기본 환경 선택

---
spring:
  profiles: local
  datasource:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/minit
    username: root
    password:
